# Copyright (c) 2026 kruthikiran2007. Licensed under the MIT License.
"""initial schema

Revision ID: 794b6339bb50
Revises: 
Create Date: 2026-10-02 07:42:02.443358

"""
from alembic import op
import sqlalchemy as sa


revision = '794b6339bb50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cve_cache',
    sa.Column('cpe', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cpe')
    )
    op.create_table('login_throttles',
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('scheduled_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_raw', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('ports_raw', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_raw', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('ports_raw', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['scheduled_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('is_reachable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('open_ports_observed', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=120), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=15), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('http_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('scheme', sa.String(length=10), nullable=True),
    sa.Column('final_url', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('redirect_chain', sa.Text(), nullable=True),
    sa.Column('server_header', sa.String(length=255), nullable=True),
    sa.Column('powered_by', sa.String(length=255), nullable=True),
    sa.Column('present_security_headers', sa.Text(), nullable=True),
    sa.Column('missing_security_headers', sa.Text(), nullable=True),
    sa.Column('redirects_to_https', sa.Boolean(), nullable=True),
    sa.Column('page_title', sa.String(length=255), nullable=True),
    sa.Column('directory_listing', sa.Boolean(), nullable=True),
    sa.Column('default_page', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id')
    )
    op.create_table('service_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id', 'check_type', name='uq_port_check')
    )
    op.create_table('tls_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=False),
    sa.Column('tls_version', sa.String(length=20), nullable=True),
    sa.Column('cipher_name', sa.String(length=80), nullable=True),
    sa.Column('cipher_bits', sa.Integer(), nullable=True),
    sa.Column('weak_cipher', sa.Boolean(), nullable=True),
    sa.Column('supports_tls10', sa.Boolean(), nullable=True),
    sa.Column('supports_tls11', sa.Boolean(), nullable=True),
    sa.Column('supports_tls12', sa.Boolean(), nullable=True),
    sa.Column('cert_subject', sa.String(length=255), nullable=True),
    sa.Column('cert_issuer', sa.String(length=255), nullable=True),
    sa.Column('cert_sans', sa.Text(), nullable=True),
    sa.Column('cert_not_after', sa.DateTime(), nullable=True),
    sa.Column('cert_expired', sa.Boolean(), nullable=True),
    sa.Column('cert_self_signed', sa.Boolean(), nullable=True),
    sa.Column('hostname_mismatch', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tls_info')
    op.drop_table('service_checks')
    op.drop_table('http_info')
    op.drop_table('findings')
    op.drop_table('ports')
    op.drop_table('assets')
    op.drop_table('scans')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('scheduled_scans')
    op.drop_table('login_throttles')
    op.drop_table('cve_cache')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
