"""scheduled scan webhooks

Revision ID: fe152a39d862
Revises: 794b6339bb50
Create Date: 2026-10-02 07:45:29.645242

"""
from alembic import op
import sqlalchemy as sa


revision = 'fe152a39d862'
down_revision = '794b6339bb50'
branch_labels = None
depends_on = None


def upgrade():
    # _ensure_columns() added this column on databases that started the
    # app during the Milestone 16 transition — don't add it twice.
    conn = op.get_bind()
    cols = [r[1] for r in
            conn.exec_driver_sql("PRAGMA table_info(scheduled_scans)")]
    if "webhook_url" not in cols:
        op.add_column('scheduled_scans',
                      sa.Column('webhook_url', sa.String(length=500),
                                nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_scans', 'webhook_url')
    # ### end Alembic commands ###
